# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChefXDoor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChefXDoor
  pod 'AWSCore'
  pod 'AWSCognito'
  pod 'AWSS3'
  pod 'AWSCognitoIdentityProvider'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod "FAPanels"
  pod 'AWSAPIGateway'
  pod 'Kingfisher', '~> 4.9.0'
  pod 'PKHUD', '~> 5.0'
  pod 'MIBlurPopup'
  pod 'FaveButton'
  pod 'FormTextField'
  pod 'MBRadioCheckboxButton'
  pod 'Fusuma'
  
  target 'ChefXDoorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChefXDoorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
